const fs = require('fs');
const indiaPath = 'src/data/indiaDestinations.js';
let indiaContent = fs.readFileSync(indiaPath, 'utf8');

const kasolObj = `  ,{
    id: 'kasol',
    name: 'Kasol',
    aliases: ['kasol', 'mini israel'],
    country: 'India',
    state: 'Himachal Pradesh',
    category: 'Nature',
    description: 'A quaint village in Parvati Valley known for its scenic beauty and Israeli culture.',
    image_url: 'https://images.unsplash.com/photo-1626714486518-e17f549c4033?w=800',
    best_season: 'Oct - Jun',
    weather_type: 'Mountain',
    weather_info: '15°C Cool',
    estimated_budget_inr: 12000,
    accommodation_cost_per_night: 2000,
    food_cost_per_day: 800,
    local_transport_cost: 500,
    sightseeing_cost: 400,
    activity_cost: 1000,
    recommended_days: 3,
    budget_level: 'Standard',
    rating: 4.6,
    review_count: 320,
    cost_tier: 'Standard',
    is_international: false,
    nearest_airport: 'Bhuntar Airport (KUU)',
    nearest_railway: 'Joginder Nagar',
    local_language: 'Hindi',
    safety_score: 9.0,
    popularity_score: 85,
    ai_score: 88,
    travel_difficulty: 'Moderate',
    highlights: ['Kheerganga Trek', 'Parvati River', 'Manikaran Sahib', 'Tosh Village'],
    hotels: [
      { name: 'The Himalayan Village', price_per_night: 5500, rating: 4.7, image: 'https://images.unsplash.com/photo-1542314831-c6a4d1409e5c?w=600', distance: 'Central', amenities: ['Spa', 'Restaurant', 'WiFi'] },
      { name: 'Parvati Kuteer', price_per_night: 3000, rating: 4.4, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600', distance: 'River side', amenities: ['WiFi', 'Restaurant'] },
      { name: 'Kasol Camps', price_per_night: 1500, rating: 4.2, image: 'https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=600', distance: 'Near market', amenities: ['Campfire', 'Trekking'] }
    ]
  }`;

indiaContent = indiaContent.replace('];', kasolObj + '\n];');
fs.writeFileSync(indiaPath, indiaContent);

const intPath = 'src/data/internationalDestinations.js';
let intContent = fs.readFileSync(intPath, 'utf8');

const additionalInt = `
  ,{
    id: 'south_korea',
    name: 'South Korea',
    aliases: ['seoul', 'busan', 'jeju'],
    country: 'South Korea',
    state: '',
    category: 'Culture',
    description: 'A vibrant country offering a mix of modern cities like Seoul and beautiful landscapes.',
    image_url: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800',
    best_season: 'Sep - Nov',
    weather_type: 'Temperate',
    weather_info: '20°C Pleasant',
    estimated_budget_inr: 85000,
    accommodation_cost_per_night: 6000,
    food_cost_per_day: 2000,
    local_transport_cost: 1500,
    sightseeing_cost: 2000,
    activity_cost: 3000,
    recommended_days: 6,
    budget_level: 'Premium',
    rating: 4.8,
    review_count: 950,
    cost_tier: 'Premium',
    is_international: true,
    nearest_airport: 'Incheon International Airport (ICN)',
    nearest_railway: 'Seoul Station',
    local_language: 'Korean',
    safety_score: 9.5,
    popularity_score: 92,
    ai_score: 95,
    travel_difficulty: 'Easy',
    highlights: ['Gyeongbokgung Palace', 'Nami Island', 'Jeju Island', 'Myeongdong Shopping'],
    hotels: [
      { name: 'Signiel Seoul', price_per_night: 15000, rating: 4.9, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600', distance: 'City Center', amenities: ['Spa', 'Pool', 'Fine Dining'] },
      { name: 'Lotte Hotel Seoul', price_per_night: 10000, rating: 4.7, image: 'https://images.unsplash.com/photo-1542314831-c6a4d1409e5c?w=600', distance: 'City Center', amenities: ['Gym', 'Restaurant'] },
      { name: 'Ibis Myeongdong', price_per_night: 6000, rating: 4.3, image: 'https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=600', distance: 'Shopping District', amenities: ['WiFi', 'Breakfast'] }
    ]
  },
  {
    id: 'sri_lanka',
    name: 'Sri Lanka',
    aliases: ['colombo', 'kandy', 'galle'],
    country: 'Sri Lanka',
    state: '',
    category: 'Nature',
    description: 'An island nation rich in wildlife, beaches, and ancient ruins.',
    image_url: 'https://images.unsplash.com/photo-1537255152778-011e48e0293d?w=800',
    best_season: 'Dec - Mar',
    weather_type: 'Tropical',
    weather_info: '27°C Warm',
    estimated_budget_inr: 45000,
    accommodation_cost_per_night: 4000,
    food_cost_per_day: 1200,
    local_transport_cost: 1000,
    sightseeing_cost: 1500,
    activity_cost: 2000,
    recommended_days: 5,
    budget_level: 'Standard',
    rating: 4.6,
    review_count: 520,
    cost_tier: 'Standard',
    is_international: true,
    nearest_airport: 'Bandaranaike International Airport (CMB)',
    nearest_railway: 'Colombo Fort',
    local_language: 'Sinhala, Tamil',
    safety_score: 8.5,
    popularity_score: 87,
    ai_score: 89,
    travel_difficulty: 'Moderate',
    highlights: ['Sigiriya Rock', 'Temple of the Tooth', 'Yala National Park', 'Galle Fort'],
    hotels: [
      { name: 'Cinnamon Grand Colombo', price_per_night: 8000, rating: 4.8, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600', distance: 'City Center', amenities: ['Pool', 'Spa'] },
      { name: 'Shangri-La Colombo', price_per_night: 12000, rating: 4.9, image: 'https://images.unsplash.com/photo-1542314831-c6a4d1409e5c?w=600', distance: 'Beachfront', amenities: ['Pool', 'Gym'] },
      { name: 'Marino Beach', price_per_night: 5000, rating: 4.5, image: 'https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=600', distance: 'Marine Drive', amenities: ['Rooftop Pool', 'WiFi'] }
    ]
  },
  {
    id: 'nepal',
    name: 'Nepal',
    aliases: ['kathmandu', 'pokhara'],
    country: 'Nepal',
    state: '',
    category: 'Adventure',
    description: 'Home to the Himalayas, offering epic trekking and spiritual temples.',
    image_url: 'https://images.unsplash.com/photo-1534065476313-09419b4fcb5a?w=800',
    best_season: 'Oct - Dec',
    weather_type: 'Mountain',
    weather_info: '15°C Cool',
    estimated_budget_inr: 30000,
    accommodation_cost_per_night: 2500,
    food_cost_per_day: 800,
    local_transport_cost: 600,
    sightseeing_cost: 1000,
    activity_cost: 2000,
    recommended_days: 6,
    budget_level: 'Budget',
    rating: 4.7,
    review_count: 630,
    cost_tier: 'Budget',
    is_international: true,
    nearest_airport: 'Tribhuvan International Airport (KTM)',
    nearest_railway: '',
    local_language: 'Nepali',
    safety_score: 9.0,
    popularity_score: 88,
    ai_score: 90,
    travel_difficulty: 'Moderate',
    highlights: ['Everest Base Camp Trek', 'Pashupatinath Temple', 'Phewa Lake', 'Swayambhunath'],
    hotels: [
      { name: 'Kathmandu Marriott', price_per_night: 10000, rating: 4.8, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600', distance: 'City Center', amenities: ['Pool', 'Spa'] },
      { name: 'Hotel Yak & Yeti', price_per_night: 7000, rating: 4.6, image: 'https://images.unsplash.com/photo-1542314831-c6a4d1409e5c?w=600', distance: 'Durbar Marg', amenities: ['Heritage', 'WiFi'] },
      { name: 'Thamel Boutique Hotel', price_per_night: 3000, rating: 4.4, image: 'https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=600', distance: 'Thamel', amenities: ['Restaurant', 'WiFi'] }
    ]
  },
  {
    id: 'bhutan',
    name: 'Bhutan',
    aliases: ['thimphu', 'paro'],
    country: 'Bhutan',
    state: '',
    category: 'Culture',
    description: 'A Buddhist kingdom on the Himalayas eastern edge, known for monasteries and fortresses.',
    image_url: 'https://images.unsplash.com/photo-1596700778854-3c81fb31fbf5?w=800',
    best_season: 'Oct - Dec',
    weather_type: 'Mountain',
    weather_info: '12°C Cool',
    estimated_budget_inr: 55000,
    accommodation_cost_per_night: 5000,
    food_cost_per_day: 1500,
    local_transport_cost: 1200,
    sightseeing_cost: 2000,
    activity_cost: 1500,
    recommended_days: 5,
    budget_level: 'Premium',
    rating: 4.8,
    review_count: 310,
    cost_tier: 'Premium',
    is_international: true,
    nearest_airport: 'Paro International Airport (PBH)',
    nearest_railway: '',
    local_language: 'Dzongkha',
    safety_score: 9.8,
    popularity_score: 84,
    ai_score: 92,
    travel_difficulty: 'Moderate',
    highlights: ['Tiger Nest Monastery', 'Punakha Dzong', 'Buddha Dordenma', 'Dochula Pass'],
    hotels: [
      { name: 'Taj Tashi Thimphu', price_per_night: 18000, rating: 4.9, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600', distance: 'City Center', amenities: ['Spa', 'Luxury Dining'] },
      { name: 'Le Meridien Paro', price_per_night: 15000, rating: 4.8, image: 'https://images.unsplash.com/photo-1542314831-c6a4d1409e5c?w=600', distance: 'Riverfront', amenities: ['Pool', 'Spa'] },
      { name: 'Hotel Druk', price_per_night: 7000, rating: 4.5, image: 'https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=600', distance: 'Central', amenities: ['Restaurant', 'WiFi'] }
    ]
  }
`;

intContent = intContent.replace('];', additionalInt + '\n];');
fs.writeFileSync(intPath, intContent);
console.log('Destinations added successfully.');
